version: '3.9'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend_foodgram
    image: hoffstern/foodgram-backend:latest
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/  
    restart: always
    container_name: foodgram_backend

  frontend:
    container_name: frontend_foodgram
    image: hoffstern/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend


  nginx:
    container_name: nginx_foodgram
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
