version: '3.9'
volumes:
  postgres_data:
  static_value:
  media_value:
  
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend_foodgram
    image: hoffstern/foodgram_backend:latest
    volumes:
      - static_value:/backend_static
      - media_value:/app/media
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  frontend:
    container_name: frontend_foodgram
    image: hoffstern/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
   
   nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles
      - media:/media/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend     

